FROM golang:latest

RUN apt-get update && apt-get install -y python3 python3-pip python3.11-venv

COPY ./Go_Example/example.go /app/BS_approach/Go_Example/example.go
COPY ./BS_approach.py /app/BS_approach/BS_approach.py
COPY ./github.com@@ethereum@@go-ethereum.txt /app/BS_approach/github.com@@ethereum@@go-ethereum.txt

WORKDIR /app/BS_approach

RUN python3 -m venv myenv && \
    /bin/bash -c "source myenv/bin/activate && \
    pip install requests packaging"